### ISSUE TITLE
ks_calculator run into error

### ISSUE THREAD

**Issue by joleneyue** [kullrich/kakscalculator2#1]
Dear Developer,
i am running the ks caculator as follows:
the input file is cds alignment file between two strains of my species i want to compare. this input file i generated with the pal2nal.pl with two strains protein file and cds files. 

./kakscalculator2/bin/KaKs_Calculator -i blasia_helsinki_potsdam_cds.aln -o blasia_helsinki_potsdam_genes_ks.txt -m YN

This is the error:
Error. The size of two sequences in 'TRINITY_DN748_c0_g3_i4.p1        GAGGCAGCTGAGATAGTTCGAGCTTGTATGGAGGGAGTGGCGTCACTGAAAGTTCCACTT' is not equal.

this gene id "TRINITY_DN748_c0_g3_i4.p1  " is the first gene id in the alignment file.  

Could you help with this?
Thanks a lot!
Cheers,
Yuling

**Comment by kullrich** [comment]
Hi, could you please provide the `blasia_helsinki_potsdam_cds.aln` file so that I could have a look.

As an alternative you could try the `MSA2dist` package, where I ported all the KaKs_Calculator code in R/Rcpp:

https://www.bioconductor.org/packages/release/bioc/html/MSA2dist.html

An example using a pal2nal fasta codon alignment would be with the `MYN` model from KaKs_Calculator:
```
cds <- Biostrings::readDNAStringSet("pal2nal.aln.fasta")
cds |> MSA2dist::dnastring2kaks(model="MYN")
```

or with the `YN` model:

```
cds <- Biostrings::readDNAStringSet("pal2nal.aln.fasta")
cds |> MSA2dist::dnastring2kaks(model="YN")
```

If there are more than two sequences in the `pal2nal.aln.fasta` file you could even use multiple threads, like:

```
cds <- Biostrings::readDNAStringSet("pal2nal.aln.fasta")
cds |> MSA2dist::dnastring2kaks(model="YN", threads=2)
```

These are the models to select:
`   model: specify codon model either "Li" or "NG86" or one of
          ‘KaKs_Calculator2’ model "NG", "LWL", "LPB", "MLWL", "MLPB",
          "GY", "YN", "MYN", "MS", "MA", "GNG", "GLWL", "GLPB",
          "GMLWL", "GMLPB", "GYN", "GMYN" [default: Li]`

Best regards

Kristian

**Comment by joleneyue** [comment]
Thanks Kristian,

I went with the wrapper paraat software for this matter, the issue is resolved .

Cheers,
Yuling

**Comment by kullrich** [comment]
Perfect, if you would need parallel support, look at the `MSA2dist` package.
If you would need to test directly with codeml, here you would find a python script that does this for your:
https://github.com/kullrich/bio-scripts/blob/master/fasta/cds2codeml.py
Best regards
Kristian
